SELECT COUNT(*) FROM farmacia;
SELECT MIN(idade) FROM usuarios;
SELECT MAX(idade) FROM usuarios;
SELECT ROUND(AVG(idade)) FROM usuarios WHERE idade>=18;
SELECT SUM(estoque) FROM farmacia WHERE categoria= 'blue' OR categoria= 'black';
SELECT SUM(estoque) FROM farmacia WHERE categoria IS NOT NULL;
SELECT SUM(estoque) FROM farmacia WHERE categoria IS NULL;
SELECT estoque FROM farmacia WHERE categoria IS NULL;
SELECT CONCAT(medicamento, ' (', categoria,')') AS fabricante FROM farmacia WHERE categoria IS NOT NULL;
SELECT CONCAT(ID, ' - ',medicamento, ' (', COALESCE(categoria,'sem categoria'),')') AS fabricante FROM farmacia;
SELECT nome, idade , CAST(cadastro AS date) FROM usuarios WHERE CAST(cadastro AS date)<CAST('2020-01-01' AS date);
SELECT nome, idade , email , AGE(CAST(cadastro AS timestamp)) FROM usuarios WHERE idade<18;
SELECT nome, idade , email , AGE(CAST(cadastro AS date)) FROM usuarios WHERE idade>=65 AND CAST(cadastro AS date) < NOW();
SELECT categoria, SUM(estoque) AS "quantidade de produtos" FROM farmacia WHERE categoria IS NOT NULL GROUP BY categoria;
SELECT idade, COUNT(id) AS "quantidade" FROM usuarios WHERE idade>=18 GROUP BY idade;
SELECT categoria, SUM(estoque) AS "quantidade de produtos" FROM farmacia WHERE categoria IS NOT NULL GROUP BY categoria LIMIT 3;