SELECT * FROM musicas;
SELECT composicao, tempo FROM musicas;
SELECT compositor, composicao FROM musicas WHERE id BETWEEM 47 AND 123;
SELECT * FROM musicas WHERE compositor is not null and tempo<500 AND compositor <> 'Bach';
SELECT composicao, tempo FROM musicas WHERE compositor = 'Mozart' OR compositor = 'Bach';
SELECT * FROM musicas ORDER BY id DESC;
SELECT * FROM musicas ORDER BY tempo DESC;
SELECT * FROM musicas ORDER BY tempo LIMIT 5;
SELECT * FROM musicas ORDER BY tempo DESC LIMIT 10;
SELECT * FROM musicas ORDER BY tempo OFFSET 5 LIMIT 10;
SELECT * FROM musicas LIMIT 10;
SELECT * FROM musicas LIMIT 10 OFFSET 10;
SELECT * FROM musicas LIMIT 10 OFFSET 20;
SELECT * FROM musicas LIMIT 10 OFFSET 30;
SELECT * FROM musicas LIMIT 12;
SELECT * FROM musicas LIMIT 12 OFFSET 12;
SELECT * FROM musicas LIMIT 12 OFFSET 24;
SELECT * FROM musicas LIMIT 12 OFFSET 36;
SELECT * FROM musicas LIMIT 12 OFFSET 48;
SELECT * FROM musicas LIMIT 12 OFFSET 60;
SELECT DISTINCT compositor  FROM musicas WHERE compositor IS NOT NULL;
SELECT DISTINCT compositor, composicao FROM musicas;
SELECT * FROM musicas WHERE compositor LIKE  'Bra%';
SELECT * FROM musicas WHERE ritmo LIKE  '%troppo';
SELECT * FROM musicas WHERE composicao ILIKE  '%quartet%';
SELECT * FROM musicas WHERE composicao  NOT ILIKE  '%quintet%';